version: "3"
services:
  database:
    image: postgres:9.6
    container_name: "register_database"
    environment:
      - POSTGRES_DB=REGISTER
      - POSTGRES_USER=gabi
      - POSTGRES_PASSWORD=123456
      - TZ=GMT
    volumes:
      - "./database/postgres:/var/lib/postgresql/data"
    ports: 
      - 5432:5432
